moduledir = get_option('prefix') / get_option('datadir') / meson.project_name() / 'popcorn' / 'widgets' / 'pages'

widgets = [
  '__init__.py',
  'login.py',
  'home.py',
  'search.py',
  'wrapbox_page.py',
  'welcome.py',
  'main.py',
  'libraries.py',
]

install_data(widgets, install_dir: moduledir)